---
title: "final_proj"
author: "Eduardo Carrasco"
date: "3/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Package names
packages <- c("DT", "knitr", "ggplot2", "ggrepel", "tidyverse", 
              "formatR", "dslabs", "janitor", "ggthemes", "readr")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
```

## Esports Data Analysis

# Initial Data Explortation
```{r echo = TRUE}
data <- read_csv("data/twitchdata-update.csv")
data <- clean_names(data, case = "snake")

head(data)
summary(data)

```
```{r echo = TRUE}
lang_table <- table(data$language)
lang_df <- as.data.frame(lang_table)
top_ten_langauges <- order(lang_df$Freq,decreasing = TRUE)[1:10]
top_ten_langauges <- lang_df[top_ten_langauges,]

#Pie Chart of the top10 languages on twitch
ggplot(top_ten_langauges, aes(x = "", y = Freq, fill = Var1))+
  geom_bar(stat = "identity", width = 1)+
  coord_polar("y", start = 0)+
  theme(legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())


```
